services:
  db:
    image: postgres:16
    container_name: olist-db
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5436"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d olist"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: