erDiagram
    CUSTOMERS ||--o{ ORDERS : faz
    ORDERS ||--o{ ORDER_ITEMS : contem
    ORDER_ITEMS }o--|| PRODUCTS : refere-se
    ORDER_ITEMS }o--|| SELLERS : vendido_por
    ORDERS ||--|| REVIEWS : recebe
    CUSTOMERS }o--|| GEOLOCATIONS : localiza
    SELLERS }o--|| GEOLOCATIONS : localiza
