CREATE TABLE IF NOT EXISTS "ORDER_ITEMS" (
    
    "order_item_id" VARCHAR(255) PRIMARY KEY,
    "product_id" VARCHAR(255) NOT NULL,
    "seller_id" VARCHAR(255) NOT NULL,
    "order_id" VARCHAR(255) NOT NULL,
    "shipping_limit_date" TIMESTAMP,
    "price" DECIMAL(10,2),
    "freight_value" DECIMAL(10,2),
    "product_category_name" VARCHAR(255),
    "product_name_lenght" INTEGER,
    "product_description_lenght" INTEGER,
    "product_photos_qty" INTEGER,
    "product_weight_g" DECIMAL(10,2),
    "product_length_cm" DECIMAL(10,2),
    "product_height_cm" DECIMAL(10,2),
    "product_width_cm" DECIMAL(10,2),
    "seller_zip_code_prefix" INTEGER,
    "seller_city" VARCHAR(255),
    "seller_state" VARCHAR(255),
    "vendedor_geolocation_lat" DECIMAL(9,6), -- Renomeado
    "vendedor_geolocation_lng" DECIMAL(9,6), -- Renomeado
    "review_comment_title" VARCHAR(255),
    "review_comment_message" TEXT,
    "customer_unique_id" VARCHAR(255) NOT NULL,
    "order_status" VARCHAR(50) NOT NULL,
    "qtd_payment_sequential" INTEGER,
    "primeiro_payment_type" VARCHAR(50),
    "valor_total_pagamento" DECIMAL(10,2),
    "maximo_payment_installments" INTEGER,
    "order_purchase_timestamp" TIMESTAMP NOT NULL,
    "order_delivered_customer_date" TIMESTAMP,
    "order_approved_at" TIMESTAMP,
    "order_delivered_carrier_date" TIMESTAMP,
    "order_estimated_delivery_date" TIMESTAMP,
    "review_score" SMALLINT,
    "review_creation_date" TIMESTAMP,
    "review_answer_timestamp" TIMESTAMP,
    "customer_zip_code_prefix" INTEGER,
    "customer_city" VARCHAR(255),
    "customer_state" VARCHAR(255),
    "cliente_geolocation_lat" DECIMAL(9,6), -- Renomeado
    "cliente_geolocation_lng" DECIMAL(9,6)  -- Renomeado
);